const VIEW_REGISTERED_USERS = "vru"; //VIEWREGISTEREDUSERS
const REGISTER_NEW_USER = "rnu";
const GET_ALL_DATABASE_DATA = "gadd";
const SUBMIT_HOURLY_PRODUCTION_REPORT = "shpr";
const VIEW_HOURLY_PRODUCTION_REPORT = "vhpr";
const LOGIN = "login";
const EDIT_USER_INFO = "eui";
const GET_NOTIFICATIONS = "gn";
const REGISTER_MACHINE = "rm";
const GET_MACHINE_LIST= "gml";

const PM_ENDPOINT = "production_manager_endpoint";
const ADMIN_ENDPOINT = "admin_endpoint";

const VALID_USER_HASH = "VALID_USER_HASH";
const INVALID_USER_HASH = "INVALID_USER_HASH";

module.exports = {VIEW_REGISTERED_USERS, REGISTER_NEW_USER, GET_ALL_DATABASE_DATA, SUBMIT_HOURLY_PRODUCTION_REPORT, VIEW_HOURLY_PRODUCTION_REPORT, LOGIN, EDIT_USER_INFO, GET_NOTIFICATIONS, REGISTER_MACHINE, GET_MACHINE_LIST, PM_ENDPOINT, VALID_USER_HASH, INVALID_USER_HASH,ADMIN_ENDPOINT }
