const VIEW_REGISTERED_USERS = "vru"; //VIEWREGISTEREDUSERS
const REGISTER_NEW_USER = "rnu";
const GET_ALL_DATABASE_DATA = "gadd";
const SUBMIT_HOURLY_PRODUCTION_REPORT = "shpr";
const VIEW_HOURLY_PRODUCTION_REPORT = "vhpr";
const LOGIN = "login";

module.exports = {VIEW_REGISTERED_USERS, REGISTER_NEW_USER, GET_ALL_DATABASE_DATA, SUBMIT_HOURLY_PRODUCTION_REPORT, VIEW_HOURLY_PRODUCTION_REPORT, LOGIN}
