const VIEW_REGISTERED_USERS = "vru"; //VIEWREGISTEREDUSERS
const REGISTER_NEW_USER = "rnu";
const GET_ALL_DATABASE_DATA = "gadd";
const SUBMIT_HOURLY_PRODUCTION_REPORT = "shpr";
const VIEW_HOURLY_PRODUCTION_REPORT = "vhpr";

const LOGIN = "login";
const LOGOUT = "logout";

const EDIT_USER_INFO = "eui";
const GET_NOTIFICATIONS = "gn";
const REGISTER_MACHINE = "rm";
const GET_MACHINE_LIST= "gml";

const PM_ENDPOINT = "production_manager_endpoint";
const ADMIN_ENDPOINT = "admin_endpoint";
const LC_ENDPOINT = "line_chief_endpoint";

const VALID_USER_HASH = "VALID_USER_HASH";
const INVALID_USER_HASH = "INVALID_USER_HASH";

const SAVE_ASSEMBLY_LINE_LAYOUT = "sall";
const GET_ASSEMBLY_LINE_LAYOUT = "gall";
const REGISTER_ASSEMBLY_LINE = "ral";
const GET_ASSEMBLY_LINE_LIST = "gallist";
const SUPERVISOR_ENDPOINT = "SUPERVISOR_ENDPOINT";

const START_NEW_PRODUCTION = "snp";

const PING = "ping";

module.exports = {VIEW_REGISTERED_USERS, REGISTER_NEW_USER, GET_ALL_DATABASE_DATA, SUBMIT_HOURLY_PRODUCTION_REPORT, VIEW_HOURLY_PRODUCTION_REPORT, LOGIN, EDIT_USER_INFO, GET_NOTIFICATIONS, REGISTER_MACHINE, GET_MACHINE_LIST, PM_ENDPOINT, VALID_USER_HASH, INVALID_USER_HASH,ADMIN_ENDPOINT, LOGOUT, SAVE_ASSEMBLY_LINE_LAYOUT, GET_ASSEMBLY_LINE_LAYOUT, REGISTER_ASSEMBLY_LINE, GET_ASSEMBLY_LINE_LIST,LC_ENDPOINT, SUPERVISOR_ENDPOINT, PING, START_NEW_PRODUCTION }
